/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as VolumesRouteImport } from './routes/volumes'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as ConnectCliRouteImport } from './routes/connect-cli'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentGuideRouteImport } from './routes/agent-guide'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as VolumesVolumeIdRouteImport } from './routes/volumes.$volumeId'
import { Route as SignupClerkPathRouteImport } from './routes/signup.$clerkPath'
import { Route as McpConnectRouteImport } from './routes/mcp_.connect'
import { Route as LoginClerkPathRouteImport } from './routes/login.$clerkPath'
import { Route as DocsWorkspacesRouteImport } from './routes/docs_.workspaces'
import { Route as DocsTypescriptSdkRouteImport } from './routes/docs_.typescript-sdk'
import { Route as DocsSelfManagedRouteImport } from './routes/docs_.self-managed'
import { Route as DocsPythonSdkRouteImport } from './routes/docs_.python-sdk'
import { Route as DocsPerformanceRouteImport } from './routes/docs_.performance'
import { Route as DocsMcpAgentsRouteImport } from './routes/docs_.mcp-agents'
import { Route as DocsLocalFilesRouteImport } from './routes/docs_.local-files'
import { Route as DocsHowItWorksRouteImport } from './routes/docs_.how-it-works'
import { Route as DocsFaqRouteImport } from './routes/docs_.faq'
import { Route as DocsCliRouteImport } from './routes/docs_.cli'
import { Route as TemplatesInstalledWorkspaceIdRouteImport } from './routes/templates.installed.$workspaceId'
import { Route as WorkspacesWorkspaceIdVolumesVolumeIdRouteImport } from './routes/workspaces_.$workspaceId.volumes.$volumeId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumesRoute = VolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCliRoute = ConnectCliRouteImport.update({
  id: '/connect-cli',
  path: '/connect-cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentGuideRoute = AgentGuideRouteImport.update({
  id: '/agent-guide',
  path: '/agent-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => WorkspacesRoute,
} as any)
const VolumesVolumeIdRoute = VolumesVolumeIdRouteImport.update({
  id: '/$volumeId',
  path: '/$volumeId',
  getParentRoute: () => VolumesRoute,
} as any)
const SignupClerkPathRoute = SignupClerkPathRouteImport.update({
  id: '/$clerkPath',
  path: '/$clerkPath',
  getParentRoute: () => SignupRoute,
} as any)
const McpConnectRoute = McpConnectRouteImport.update({
  id: '/mcp_/connect',
  path: '/mcp/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClerkPathRoute = LoginClerkPathRouteImport.update({
  id: '/$clerkPath',
  path: '/$clerkPath',
  getParentRoute: () => LoginRoute,
} as any)
const DocsWorkspacesRoute = DocsWorkspacesRouteImport.update({
  id: '/docs_/workspaces',
  path: '/docs/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTypescriptSdkRoute = DocsTypescriptSdkRouteImport.update({
  id: '/docs_/typescript-sdk',
  path: '/docs/typescript-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSelfManagedRoute = DocsSelfManagedRouteImport.update({
  id: '/docs_/self-managed',
  path: '/docs/self-managed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPythonSdkRoute = DocsPythonSdkRouteImport.update({
  id: '/docs_/python-sdk',
  path: '/docs/python-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPerformanceRoute = DocsPerformanceRouteImport.update({
  id: '/docs_/performance',
  path: '/docs/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsMcpAgentsRoute = DocsMcpAgentsRouteImport.update({
  id: '/docs_/mcp-agents',
  path: '/docs/mcp-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLocalFilesRoute = DocsLocalFilesRouteImport.update({
  id: '/docs_/local-files',
  path: '/docs/local-files',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHowItWorksRoute = DocsHowItWorksRouteImport.update({
  id: '/docs_/how-it-works',
  path: '/docs/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/docs_/faq',
  path: '/docs/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs_/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesInstalledWorkspaceIdRoute =
  TemplatesInstalledWorkspaceIdRouteImport.update({
    id: '/installed/$workspaceId',
    path: '/installed/$workspaceId',
    getParentRoute: () => TemplatesRoute,
  } as any)
const WorkspacesWorkspaceIdVolumesVolumeIdRoute =
  WorkspacesWorkspaceIdVolumesVolumeIdRouteImport.update({
    id: '/workspaces_/$workspaceId/volumes/$volumeId',
    path: '/workspaces/$workspaceId/volumes/$volumeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/volumes': typeof VolumesRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/local-files': typeof DocsLocalFilesRoute
  '/docs/mcp-agents': typeof DocsMcpAgentsRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/self-managed': typeof DocsSelfManagedRoute
  '/docs/typescript-sdk': typeof DocsTypescriptSdkRoute
  '/docs/workspaces': typeof DocsWorkspacesRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/mcp/connect': typeof McpConnectRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/templates/installed/$workspaceId': typeof TemplatesInstalledWorkspaceIdRoute
  '/workspaces/$workspaceId/volumes/$volumeId': typeof WorkspacesWorkspaceIdVolumesVolumeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/volumes': typeof VolumesRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/docs/cli': typeof DocsCliRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/how-it-works': typeof DocsHowItWorksRoute
  '/docs/local-files': typeof DocsLocalFilesRoute
  '/docs/mcp-agents': typeof DocsMcpAgentsRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/self-managed': typeof DocsSelfManagedRoute
  '/docs/typescript-sdk': typeof DocsTypescriptSdkRoute
  '/docs/workspaces': typeof DocsWorkspacesRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/mcp/connect': typeof McpConnectRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/templates/installed/$workspaceId': typeof TemplatesInstalledWorkspaceIdRoute
  '/workspaces/$workspaceId/volumes/$volumeId': typeof WorkspacesWorkspaceIdVolumesVolumeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/agent-guide': typeof AgentGuideRoute
  '/agents': typeof AgentsRoute
  '/api-keys': typeof ApiKeysRoute
  '/connect-cli': typeof ConnectCliRoute
  '/databases': typeof DatabasesRoute
  '/docs': typeof DocsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRouteWithChildren
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRouteWithChildren
  '/templates': typeof TemplatesRouteWithChildren
  '/volumes': typeof VolumesRouteWithChildren
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/docs_/cli': typeof DocsCliRoute
  '/docs_/faq': typeof DocsFaqRoute
  '/docs_/how-it-works': typeof DocsHowItWorksRoute
  '/docs_/local-files': typeof DocsLocalFilesRoute
  '/docs_/mcp-agents': typeof DocsMcpAgentsRoute
  '/docs_/performance': typeof DocsPerformanceRoute
  '/docs_/python-sdk': typeof DocsPythonSdkRoute
  '/docs_/self-managed': typeof DocsSelfManagedRoute
  '/docs_/typescript-sdk': typeof DocsTypescriptSdkRoute
  '/docs_/workspaces': typeof DocsWorkspacesRoute
  '/login/$clerkPath': typeof LoginClerkPathRoute
  '/mcp_/connect': typeof McpConnectRoute
  '/signup/$clerkPath': typeof SignupClerkPathRoute
  '/volumes/$volumeId': typeof VolumesVolumeIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/templates/installed/$workspaceId': typeof TemplatesInstalledWorkspaceIdRoute
  '/workspaces_/$workspaceId/volumes/$volumeId': typeof WorkspacesWorkspaceIdVolumesVolumeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/agent-guide'
    | '/agents'
    | '/api-keys'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/volumes'
    | '/workspaces'
    | '/docs/cli'
    | '/docs/faq'
    | '/docs/how-it-works'
    | '/docs/local-files'
    | '/docs/mcp-agents'
    | '/docs/performance'
    | '/docs/python-sdk'
    | '/docs/self-managed'
    | '/docs/typescript-sdk'
    | '/docs/workspaces'
    | '/login/$clerkPath'
    | '/mcp/connect'
    | '/signup/$clerkPath'
    | '/volumes/$volumeId'
    | '/workspaces/$workspaceId'
    | '/templates/installed/$workspaceId'
    | '/workspaces/$workspaceId/volumes/$volumeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/agent-guide'
    | '/agents'
    | '/api-keys'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/volumes'
    | '/workspaces'
    | '/docs/cli'
    | '/docs/faq'
    | '/docs/how-it-works'
    | '/docs/local-files'
    | '/docs/mcp-agents'
    | '/docs/performance'
    | '/docs/python-sdk'
    | '/docs/self-managed'
    | '/docs/typescript-sdk'
    | '/docs/workspaces'
    | '/login/$clerkPath'
    | '/mcp/connect'
    | '/signup/$clerkPath'
    | '/volumes/$volumeId'
    | '/workspaces/$workspaceId'
    | '/templates/installed/$workspaceId'
    | '/workspaces/$workspaceId/volumes/$volumeId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/agent-guide'
    | '/agents'
    | '/api-keys'
    | '/connect-cli'
    | '/databases'
    | '/docs'
    | '/downloads'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/signup'
    | '/templates'
    | '/volumes'
    | '/workspaces'
    | '/docs_/cli'
    | '/docs_/faq'
    | '/docs_/how-it-works'
    | '/docs_/local-files'
    | '/docs_/mcp-agents'
    | '/docs_/performance'
    | '/docs_/python-sdk'
    | '/docs_/self-managed'
    | '/docs_/typescript-sdk'
    | '/docs_/workspaces'
    | '/login/$clerkPath'
    | '/mcp_/connect'
    | '/signup/$clerkPath'
    | '/volumes/$volumeId'
    | '/workspaces/$workspaceId'
    | '/templates/installed/$workspaceId'
    | '/workspaces_/$workspaceId/volumes/$volumeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AgentGuideRoute: typeof AgentGuideRoute
  AgentsRoute: typeof AgentsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ConnectCliRoute: typeof ConnectCliRoute
  DatabasesRoute: typeof DatabasesRoute
  DocsRoute: typeof DocsRoute
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRouteWithChildren
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRouteWithChildren
  TemplatesRoute: typeof TemplatesRouteWithChildren
  VolumesRoute: typeof VolumesRouteWithChildren
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  DocsCliRoute: typeof DocsCliRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsHowItWorksRoute: typeof DocsHowItWorksRoute
  DocsLocalFilesRoute: typeof DocsLocalFilesRoute
  DocsMcpAgentsRoute: typeof DocsMcpAgentsRoute
  DocsPerformanceRoute: typeof DocsPerformanceRoute
  DocsPythonSdkRoute: typeof DocsPythonSdkRoute
  DocsSelfManagedRoute: typeof DocsSelfManagedRoute
  DocsTypescriptSdkRoute: typeof DocsTypescriptSdkRoute
  DocsWorkspacesRoute: typeof DocsWorkspacesRoute
  McpConnectRoute: typeof McpConnectRoute
  WorkspacesWorkspaceIdVolumesVolumeIdRoute: typeof WorkspacesWorkspaceIdVolumesVolumeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volumes': {
      id: '/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof VolumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-cli': {
      id: '/connect-cli'
      path: '/connect-cli'
      fullPath: '/connect-cli'
      preLoaderRoute: typeof ConnectCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-guide': {
      id: '/agent-guide'
      path: '/agent-guide'
      fullPath: '/agent-guide'
      preLoaderRoute: typeof AgentGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/volumes/$volumeId': {
      id: '/volumes/$volumeId'
      path: '/$volumeId'
      fullPath: '/volumes/$volumeId'
      preLoaderRoute: typeof VolumesVolumeIdRouteImport
      parentRoute: typeof VolumesRoute
    }
    '/signup/$clerkPath': {
      id: '/signup/$clerkPath'
      path: '/$clerkPath'
      fullPath: '/signup/$clerkPath'
      preLoaderRoute: typeof SignupClerkPathRouteImport
      parentRoute: typeof SignupRoute
    }
    '/mcp_/connect': {
      id: '/mcp_/connect'
      path: '/mcp/connect'
      fullPath: '/mcp/connect'
      preLoaderRoute: typeof McpConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$clerkPath': {
      id: '/login/$clerkPath'
      path: '/$clerkPath'
      fullPath: '/login/$clerkPath'
      preLoaderRoute: typeof LoginClerkPathRouteImport
      parentRoute: typeof LoginRoute
    }
    '/docs_/workspaces': {
      id: '/docs_/workspaces'
      path: '/docs/workspaces'
      fullPath: '/docs/workspaces'
      preLoaderRoute: typeof DocsWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/typescript-sdk': {
      id: '/docs_/typescript-sdk'
      path: '/docs/typescript-sdk'
      fullPath: '/docs/typescript-sdk'
      preLoaderRoute: typeof DocsTypescriptSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/self-managed': {
      id: '/docs_/self-managed'
      path: '/docs/self-managed'
      fullPath: '/docs/self-managed'
      preLoaderRoute: typeof DocsSelfManagedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/python-sdk': {
      id: '/docs_/python-sdk'
      path: '/docs/python-sdk'
      fullPath: '/docs/python-sdk'
      preLoaderRoute: typeof DocsPythonSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/performance': {
      id: '/docs_/performance'
      path: '/docs/performance'
      fullPath: '/docs/performance'
      preLoaderRoute: typeof DocsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/mcp-agents': {
      id: '/docs_/mcp-agents'
      path: '/docs/mcp-agents'
      fullPath: '/docs/mcp-agents'
      preLoaderRoute: typeof DocsMcpAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/local-files': {
      id: '/docs_/local-files'
      path: '/docs/local-files'
      fullPath: '/docs/local-files'
      preLoaderRoute: typeof DocsLocalFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/how-it-works': {
      id: '/docs_/how-it-works'
      path: '/docs/how-it-works'
      fullPath: '/docs/how-it-works'
      preLoaderRoute: typeof DocsHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/faq': {
      id: '/docs_/faq'
      path: '/docs/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/cli': {
      id: '/docs_/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/installed/$workspaceId': {
      id: '/templates/installed/$workspaceId'
      path: '/installed/$workspaceId'
      fullPath: '/templates/installed/$workspaceId'
      preLoaderRoute: typeof TemplatesInstalledWorkspaceIdRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/workspaces_/$workspaceId/volumes/$volumeId': {
      id: '/workspaces_/$workspaceId/volumes/$volumeId'
      path: '/workspaces/$workspaceId/volumes/$volumeId'
      fullPath: '/workspaces/$workspaceId/volumes/$volumeId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVolumesVolumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginClerkPathRoute: typeof LoginClerkPathRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginClerkPathRoute: LoginClerkPathRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface SignupRouteChildren {
  SignupClerkPathRoute: typeof SignupClerkPathRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupClerkPathRoute: SignupClerkPathRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface TemplatesRouteChildren {
  TemplatesInstalledWorkspaceIdRoute: typeof TemplatesInstalledWorkspaceIdRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesInstalledWorkspaceIdRoute: TemplatesInstalledWorkspaceIdRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface VolumesRouteChildren {
  VolumesVolumeIdRoute: typeof VolumesVolumeIdRoute
}

const VolumesRouteChildren: VolumesRouteChildren = {
  VolumesVolumeIdRoute: VolumesVolumeIdRoute,
}

const VolumesRouteWithChildren =
  VolumesRoute._addFileChildren(VolumesRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AgentGuideRoute: AgentGuideRoute,
  AgentsRoute: AgentsRoute,
  ApiKeysRoute: ApiKeysRoute,
  ConnectCliRoute: ConnectCliRoute,
  DatabasesRoute: DatabasesRoute,
  DocsRoute: DocsRoute,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRouteWithChildren,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRouteWithChildren,
  TemplatesRoute: TemplatesRouteWithChildren,
  VolumesRoute: VolumesRouteWithChildren,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  DocsCliRoute: DocsCliRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsHowItWorksRoute: DocsHowItWorksRoute,
  DocsLocalFilesRoute: DocsLocalFilesRoute,
  DocsMcpAgentsRoute: DocsMcpAgentsRoute,
  DocsPerformanceRoute: DocsPerformanceRoute,
  DocsPythonSdkRoute: DocsPythonSdkRoute,
  DocsSelfManagedRoute: DocsSelfManagedRoute,
  DocsTypescriptSdkRoute: DocsTypescriptSdkRoute,
  DocsWorkspacesRoute: DocsWorkspacesRoute,
  McpConnectRoute: McpConnectRoute,
  WorkspacesWorkspaceIdVolumesVolumeIdRoute:
    WorkspacesWorkspaceIdVolumesVolumeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
